force-app/main/default/objects/Trigger_Configuration__mdt/Trigger_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>https://www.linkedin.com/pulse/custom-metadata-type-switches-bypassing-record-trigger-stuart-werner/</description>
    <label>Trigger Configuration</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Configuration__mdt/fields/Bypass_User__c.field-meta.xml
<CustomField>
    <fullName>Bypass_User__c</fullName>
    <description>Contains the username of the running user that can potentially bypass the execution of the trigger.</description>
    <label>Bypass User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Configuration__mdt/fields/Is_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Switch to toggle the trigger (or flow) on and off.</description>
    <label>Is Trigger Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Configuration__mdt/fields/Trigger_Name__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name__c</fullName>
    <label>Trigger Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TriggerConfigTestDataFactoryTest.cls
@isTest
private class TriggerConfigTestDataFactoryTest {

    @isTest
    static void testBuildSingleRecord() {
        // Arrange
        String triggerName = 'PvpTrigger';
        Boolean isTriggerEnabled = true;
        String bypassUserId = '005123456789012345';

        TriggerConfigTestDataFactory factory = new TriggerConfigTestDataFactory()
                                                .withTriggerName(triggerName)
                                                .withIsTriggerEnabled(isTriggerEnabled)
                                                .withBypassUserId(bypassUserId);

        // Act
        Trigger_Configuration__mdt record = factory.build();

        // Assert
        Assert.areEqual(triggerName, record.DeveloperName, 'DeveloperName should match the input value');
        Assert.areEqual(triggerName, record.Trigger_Name__c, 'Trigger_Name__c should match the input value');
        Assert.areEqual(isTriggerEnabled, record.Is_Trigger_Enabled__c, 'Is_Trigger_Enabled__c should match the input value');
        Assert.areEqual(bypassUserId, record.Bypass_User__c, 'Bypass_User__c should match the input value');
    }
}