force-app/main/default/objects/Trigger_Configuration__mdt/Trigger_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>https://www.linkedin.com/pulse/custom-metadata-type-switches-bypassing-record-trigger-stuart-werner/</description>
    <label>Trigger Configuration</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Configuration__mdt/fields/Bypass_User__c.field-meta.xml
<CustomField>
    <fullName>Bypass_User__c</fullName>
    <description>Contains the username of the running user that can potentially bypass the execution of the trigger.</description>
    <label>Bypass User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Configuration__mdt/fields/Is_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Switch to toggle the trigger (or flow) on and off.</description>
    <label>Is Trigger Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Configuration__mdt/fields/Trigger_Name__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Name__c</fullName>
    <label>Trigger Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TriggerConfigTestDataFactory.cls
public class TriggerConfigTestDataFactory {
    private final static String MY_TRIGGER_NAME = 'MyTrigger'; // Default value, can/should be overwritten using withTriggerName
    
    private Trigger_Configuration__mdt record;

    public TriggerConfigTestDataFactory() {
        record = new Trigger_Configuration__mdt();
        record.DeveloperName = MY_TRIGGER_NAME;
        record.Trigger_Name__c = MY_TRIGGER_NAME;
        record.Is_Trigger_Enabled__c = true;
        record.Bypass_User__c = null;
    }

    public TriggerConfigTestDataFactory withTriggerName(String triggerName) {
        record.Trigger_Name__c = triggerName;
        record.DeveloperName = triggerName;
        return this;
    }

    public TriggerConfigTestDataFactory withIsTriggerEnabled(Boolean isTriggerEnabled) {
        record.Is_Trigger_Enabled__c = isTriggerEnabled;
        return this;
    }

    public TriggerConfigTestDataFactory withBypassUserId(String bypassUserId) {
        record.Bypass_User__c = bypassUserId;
        return this;
    }

    public Trigger_Configuration__mdt build() {
        Trigger_Configuration__mdt builtRecord = record.clone(false, false, false, false);
        record = new Trigger_Configuration__mdt();  // Reinitialize to ensure a fresh record for each build
        return builtRecord;
    }
}