force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/Leads_to_Campaigns_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configures the grouping of Leads in a Campaign as Campaign Members.</description>
    <label>Leads to Campaigns Config</label>
    <pluralLabel>Leads to Campaigns Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Defaul_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Defaul_Status__c</fullName>
    <description>Initial Status that the created Campaigns will automatically get.</description>
    <label>Campaign Defaul Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Member_Default_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Default_Status__c</fullName>
    <description>Initial Status that the Campaign Members will get when created automatically.</description>
    <label>Campaign Member Default Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Name_Delimiter__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name_Delimiter__c</fullName>
    <description>Character(s) used as field delimiter in the Campaign Name.</description>
    <label>Campaign Name Delimiter</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name_Prefix__c</fullName>
    <description>Helps identify that this Campaign is used for grouping Leads.</description>
    <label>Campaign Name Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>Leads from this source will be added to this type of Campaign as Campaign Members.</description>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foobar</fullName>
                <default>true</default>
                <label>Foobar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Time_Format__c.field-meta.xml
<CustomField>
    <fullName>Time_Format__c</fullName>
    <description>Format of the Campaign creation timestamp, used as part of the Campaign name.</description>
    <label>Time Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>yyyyMMddHHmmss</fullName>
                <default>true</default>
                <label>yyyyMMddHHmmss</label>
            </value>
            <value>
                <fullName>yyyy-MM-dd HH:mm:ss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Time_Interval_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Interval_in_Minutes__c</fullName>
    <description>The time interval since the Lead list when the inserted Leads are still assigned to the existing Campaing. It is calculated by adding this number of minutes to the creation datetime of the first Lead.</description>
    <label>Time Interval in Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadsToCampaignsConfigTestDataFactoryTes.cls
/**
 * Test class created using the Arrange-Act-Assert (AAA) Pattern.
 */
@isTest
private class LeadsToCampaignsConfigTestDataFactoryTes {

    @isTest
    static void testBuildSingleRecord() {
        // Arrange
        String cmtRecordName = 'MycmtRecordName';
        Integer timeIntervalInMinutes = 1;
        String leadSource = 'MyleadSource';
        String campaignNamePrefix = 'MycampaignNamePrefix';
        String campaignNameDelimiter = '#';
        String timeFormat = 'HHmmss yyyyMMdd';
        String campaignDefaultStatus = 'In Progress';
        String campaignMemberDefaultStatus = 'Received';

        LeadsToCampaignsConfigTestDataFactory factory = new LeadsToCampaignsConfigTestDataFactory()
                                                .withDeveloperName(cmtRecordName)
                                                .withTimeIntervalInMinutes(timeIntervalInMinutes)
                                                .withLeadSource(leadSource)
                                                .withCampaignNamePrefix(campaignNamePrefix)
                                                .withCampaignNameDelimiter(campaignNameDelimiter)
                                                .withTimeFormat(timeFormat)
                                                .withCampaignDefaultStatus(campaignDefaultStatus)
                                                .withCampaignMemberDefaultStatus(campaignMemberDefaultStatus);

        // Act
        Test.startTest();
        Leads_to_Campaigns_Config__mdt record = factory.build();
        Test.stopTest();

        // Assert
        Assert.areEqual(cmtRecordName, record.DeveloperName, 'DeveloperName should match the input value');
        Assert.areEqual(timeIntervalInMinutes, record.Time_Interval_in_Minutes__c, 'Time_Interval_in_Minutes__c should match the input value');
        Assert.areEqual(leadSource, record.Lead_Source__c, 'Lead_Source__c should match the input value');
        Assert.areEqual(campaignNamePrefix, record.Campaign_Name_Prefix__c, 'Campaign_Name_Prefix__c should match the input value');
        Assert.areEqual(campaignNameDelimiter, record.Campaign_Name_Delimiter__c, 'Campaign_Name_Delimiter__c should match the input value');
        Assert.areEqual(timeFormat, record.Time_Format__c, 'Time_Format__c should match the input value');
        Assert.areEqual(campaignDefaultStatus, record.Campaign_Defaul_Status__c, 'Campaign_Defaul_Status__c should match the input value');
        Assert.areEqual(campaignMemberDefaultStatus, record.Campaign_Member_Default_Status__c, 'Campaign_Member_Default_Status__c should match the input value');
    }
}