force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/Leads_to_Campaigns_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configures the grouping of Leads in a Campaign as Campaign Members.</description>
    <label>Leads to Campaigns Config</label>
    <pluralLabel>Leads to Campaigns Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Defaul_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Defaul_Status__c</fullName>
    <description>Initial Status that the created Campaigns will automatically get.</description>
    <label>Campaign Defaul Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Member_Default_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Default_Status__c</fullName>
    <description>Initial Status that the Campaign Members will get when created automatically.</description>
    <label>Campaign Member Default Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Name_Delimiter__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name_Delimiter__c</fullName>
    <description>Character(s) used as field delimiter in the Campaign Name.</description>
    <label>Campaign Name Delimiter</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name_Prefix__c</fullName>
    <description>Helps identify that this Campaign is used for grouping Leads.</description>
    <label>Campaign Name Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>Leads from this source will be added to this type of Campaign as Campaign Members.</description>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foobar</fullName>
                <default>true</default>
                <label>Foobar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Time_Format__c.field-meta.xml
<CustomField>
    <fullName>Time_Format__c</fullName>
    <description>Format of the Campaign creation timestamp, used as part of the Campaign name.</description>
    <label>Time Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>yyyyMMddHHmmss</fullName>
                <default>true</default>
                <label>yyyyMMddHHmmss</label>
            </value>
            <value>
                <fullName>yyyy-MM-dd HH:mm:ss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Time_Interval_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Interval_in_Minutes__c</fullName>
    <description>The time interval since the Lead list when the inserted Leads are still assigned to the existing Campaing. It is calculated by adding this number of minutes to the creation datetime of the first Lead.</description>
    <label>Time Interval in Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadsToCampaignsConfigTestDataFactory.cls
/**
 * Test Data Factory class created using the Builder Pattern.
 */
public class LeadsToCampaignsConfigTestDataFactory {
    private final static String DEFAULT_CMT_RECORD_NAME = 'Foobar'; // Default value, can/should be overwritten using withDeveloperName and withLeadSource
    private final static String DEFAULT_CAMPAIGN_NAME_PREFIX = 'Foobar -'; // Default value, can/should be overwritten using withCampaignNamePrefix
    private final static String DEFAULT_CAMPAIGN_DEFAULT_STATUS = 'Planned'; // Default value, can/should be overwritten using withCampaignDefaultStatus
    private final static String DEFAULT_CAMPAIGN_MEMBER_DEFAULT_STATUS = 'Sent'; // Default value, can/should be overwritten using withCampaignMemberDefaultStatus
    
    private Leads_to_Campaigns_Config__mdt record;

    public LeadsToCampaignsConfigTestDataFactory() {
        record = new Leads_to_Campaigns_Config__mdt();
        record.DeveloperName = DEFAULT_CMT_RECORD_NAME;
        record.Time_Interval_in_Minutes__c = 5;
        record.Lead_Source__c = DEFAULT_CMT_RECORD_NAME;
        record.Campaign_Name_Prefix__c = DEFAULT_CAMPAIGN_NAME_PREFIX;
        record.Campaign_Defaul_Status__c = DEFAULT_CAMPAIGN_DEFAULT_STATUS;
        record.Campaign_Member_Default_Status__c = DEFAULT_CAMPAIGN_MEMBER_DEFAULT_STATUS;
    }

    public LeadsToCampaignsConfigTestDataFactory withDeveloperName(String cmtRecordName) {
        record.DeveloperName = cmtRecordName;
        return this;
    }

    public LeadsToCampaignsConfigTestDataFactory withTimeIntervalInMinutes(Integer timeIntervalInMinutes) {
        record.Time_Interval_in_Minutes__c = timeIntervalInMinutes;
        return this;
    }

    public LeadsToCampaignsConfigTestDataFactory withLeadSource(String leadSource) {
        record.Lead_Source__c = leadSource;
        return this;
    }

    public LeadsToCampaignsConfigTestDataFactory withCampaignNamePrefix(String campaignNamePrefix) {
        record.Campaign_Name_Prefix__c = campaignNamePrefix;
        return this;
    }

    public LeadsToCampaignsConfigTestDataFactory withCampaignNameDelimiter(String campaignNameDelimiter) {
        record.Campaign_Name_Delimiter__c = campaignNameDelimiter;
        return this;
    }

    public LeadsToCampaignsConfigTestDataFactory withTimeFormat(String timeFormat) {
        record.Time_Format__c = timeFormat;
        return this;
    }

    public LeadsToCampaignsConfigTestDataFactory withCampaignDefaultStatus(String campaignDefaultStatus) {
        record.Campaign_Defaul_Status__c = campaignDefaultStatus;
        return this;
    }

    public LeadsToCampaignsConfigTestDataFactory withCampaignMemberDefaultStatus(String campaignMemberDefaultStatus) {
        record.Campaign_Member_Default_Status__c = campaignMemberDefaultStatus;
        return this;
    }

    public Leads_to_Campaigns_Config__mdt build() {
        Leads_to_Campaigns_Config__mdt builtRecord = record.clone(false, false, false, false);
        record = new Leads_to_Campaigns_Config__mdt();  // Reinitialize to ensure a fresh record for each build
        return builtRecord;
    }
}