force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/Leads_to_Campaigns_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configures the grouping of Leads in a Campaign as Campaign Members.</description>
    <label>Leads to Campaigns Config</label>
    <pluralLabel>Leads to Campaigns Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Defaul_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Defaul_Status__c</fullName>
    <description>Initial Status that the created Campaigns will automatically get.</description>
    <label>Campaign Defaul Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Member_Default_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Default_Status__c</fullName>
    <description>Initial Status that the Campaign Members will get when created automatically.</description>
    <label>Campaign Member Default Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
                <default>true</default>
                <label>Sent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Campaign_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name_Prefix__c</fullName>
    <description>Helps identify that this Campaign is used for grouping Leads.</description>
    <label>Campaign Name Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>Leads from this source will be added to this type of Campaign as Campaign Members.</description>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foobar</fullName>
                <default>true</default>
                <label>Foobar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leads_to_Campaigns_Config__mdt/fields/Time_Interval_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Time_Interval_in_Minutes__c</fullName>
    <description>The time interval since the Lead list when the inserted Leads are still assigned to the existing Campaing. It is calculated by adding this number of minutes to the creation datetime of the first Lead.</description>
    <label>Time Interval in Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadsToCampaignsConfigHelperTest.cls
/**
 * Test class created using the Arrange-Act-Assert (AAA) Pattern.
 */
@IsTest
public class LeadsToCampaignsConfigHelperTest {

    @isTest
    static void testgetConfigNonExistingClass() {
        // Arrange
        String cmtRecordName = 'Test_Non-ExistingClass';

        // Act
        Test.startTest();
        Leads_to_Campaigns_Config__mdt retrievedConfig = LeadsToCampaignsConfigHelper.getConfig(cmtRecordName);
        Test.stopTest();

        // Assert
        Assert.isNull(retrievedConfig.DeveloperName, 'DeveloperName should be null, because the corresponding Leads_to_Campaigns_Config__mdt record does not exist.');
        Assert.areEqual(0, retrievedConfig.Time_Interval_in_Minutes__c, 'Time_Interval_in_Minutes__c should be the default 0, because the corresponding Leads_to_Campaigns_Config__mdt record does not exist.');
    }

    @isTest
    static void testgetConfigExistingClass() {
        // Arrange
        String cmtRecordName = 'Foobar';

        // Act
        Test.startTest();
        Leads_to_Campaigns_Config__mdt retrievedConfig = LeadsToCampaignsConfigHelper.getConfig(cmtRecordName);
        Test.stopTest();

        // Assert
        Assert.areEqual(cmtRecordName, retrievedConfig.DeveloperName, 'DeveloperName should match the input.');
    }

    @isTest
    static void testGetTimeIntervalInMinutes() {
        // Arrange
        String cmtRecordName = 'Foobar';
        Integer timeIntervalInMinutes = 5;
        Leads_to_Campaigns_Config__mdt newConfig = new LeadsToCampaignsConfigTestDataFactory()
                                                    .withDeveloperName(cmtRecordName)
                                                    .withTimeIntervalInMinutes(timeIntervalInMinutes)
                                                    .build();

        // Act
        Test.startTest();
        Integer retrievedTimeIntervalInMinutes = (Integer)LeadsToCampaignsConfigHelper.getTimeIntervalInMinutes(newConfig);
        Test.stopTest();

        // Assert
        Assert.areEqual(cmtRecordName, newConfig.DeveloperName, 'DeveloperName should match the input.');
        Assert.areEqual(retrievedTimeIntervalInMinutes, newConfig.Time_Interval_in_Minutes__c, 'Time_Interval_in_Minutes__c should match the input.');
        Assert.areEqual(retrievedTimeIntervalInMinutes, timeIntervalInMinutes, 'Time_Interval_in_Minutes__c should match the input.');
    }

    @isTest
    static void testGetLeadSource() {
        // Arrange
        String cmtRecordName = 'Foobar';
        String leadSource = 'Foobar';
        Leads_to_Campaigns_Config__mdt newConfig = new LeadsToCampaignsConfigTestDataFactory()
                                                    .withDeveloperName(cmtRecordName)
                                                    .withLeadSource(leadSource)
                                                    .build();

        // Act
        Test.startTest();
        String retrievedLeadSource = LeadsToCampaignsConfigHelper.getLeadSource(newConfig);
        Test.stopTest();

        // Assert
        Assert.areEqual(cmtRecordName, newConfig.DeveloperName, 'DeveloperName should match the input.');
        Assert.areEqual(retrievedLeadSource, newConfig.Lead_Source__c, 'Lead_Source__c should match the input.');
        Assert.areEqual(retrievedLeadSource, leadSource, 'Lead_Source__c should match the input.');
    }

    @isTest
    static void testGetCampaignNamePrefix() {
        // Arrange
        String cmtRecordName = 'Foobar';
        String campaignNamePrefix = 'Foobar -';
        Leads_to_Campaigns_Config__mdt newConfig = new LeadsToCampaignsConfigTestDataFactory()
                                                    .withDeveloperName(cmtRecordName)
                                                    .withCampaignNamePrefix(campaignNamePrefix)
                                                    .build();

        // Act
        Test.startTest();
        String retrievedCampaignNamePrefix = LeadsToCampaignsConfigHelper.getCampaignNamePrefix(newConfig);
        Test.stopTest();

        // Assert
        Assert.areEqual(cmtRecordName, newConfig.DeveloperName, 'DeveloperName should match the input.');
        Assert.areEqual(retrievedCampaignNamePrefix, newConfig.Campaign_Name_Prefix__c, 'Campaign_Name_Prefix__c should match the input.');
        Assert.areEqual(retrievedCampaignNamePrefix, campaignNamePrefix, 'Campaign_Name_Prefix__c should match the input.');
    }

    @isTest
    static void testGetCampaignDefaultStatus() {
        // Arrange
        String cmtRecordName = 'Foobar';
        String campaignDefaultStatus = 'Planned';
        Leads_to_Campaigns_Config__mdt newConfig = new LeadsToCampaignsConfigTestDataFactory()
                                                    .withDeveloperName(cmtRecordName)
                                                    .withCampaignDefaultStatus(campaignDefaultStatus)
                                                    .build();

        // Act
        Test.startTest();
        String retrievedCampaignDefaultStatus = LeadsToCampaignsConfigHelper.getCampaignDefaultStatus(newConfig);
        Test.stopTest();

        // Assert
        Assert.areEqual(cmtRecordName, newConfig.DeveloperName, 'DeveloperName should match the input.');
        Assert.areEqual(retrievedCampaignDefaultStatus, newConfig.Campaign_Defaul_Status__c, 'Campaign_Defaul_Status__c should match the input.');
        Assert.areEqual(retrievedCampaignDefaultStatus, campaignDefaultStatus, 'Campaign_Defaul_Status__c should match the input.');
    }

    @isTest
    static void testGetCampaignMemberDefaultStatus() {
        // Arrange
        String cmtRecordName = 'Foobar';
        String campaignMemberDefaultStatus = 'Foobar -';
        Leads_to_Campaigns_Config__mdt newConfig = new LeadsToCampaignsConfigTestDataFactory()
                                                    .withDeveloperName(cmtRecordName)
                                                    .withCampaignMemberDefaultStatus(campaignMemberDefaultStatus)
                                                    .build();

        // Act
        Test.startTest();
        String retrievedCampaignMemberDefaultStatus = LeadsToCampaignsConfigHelper.getCampaignMemberDefaultStatus(newConfig);
        Test.stopTest();

        // Assert
        Assert.areEqual(cmtRecordName, newConfig.DeveloperName, 'DeveloperName should match the input.');
        Assert.areEqual(retrievedCampaignMemberDefaultStatus, newConfig.Campaign_Member_Default_Status__c, 'Campaign_Member_Default_Status__c should match the input.');
        Assert.areEqual(retrievedCampaignMemberDefaultStatus, campaignMemberDefaultStatus, 'Campaign_Member_Default_Status__c should match the input.');
    }
}